# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os: linux
dist: trusty
sudo: required

os: osx
osx_image: xcode8

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'